name: pomodoro-timer
services:
  frontend:
    build:
      context: ./pomodoro-frontend
      dockerfile: Dockerfile
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=pomodoro.ytkacpersky.de
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=pomodoro.ytkacpersky.de
      - LETSENCRYPT_EMAIL=letsencrypt@ytkacpersky.de

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=pomodoro-be.ytkacpersky.de
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=pomodoro-be.ytkacpersky.de
      - LETSENCRYPT_EMAIL=letsencrypt@ytkacpersky.de

networks:
  default:
    external:
      name: compose-net
